### ISSUE TITLE
vagrant-omnibus prevents most vagrant commands working while rubygems.org is having issues

### ISSUE THREAD

**Issue by jmartelletti** [chef-boneyard/vagrant-omnibus#113]
It appears that rubygems.org is currently having an issue which causes the attached exception and prevents most vagrant commands from completing successfully. The workaround is to disable your "config.omnibus.chef_version" setting temporarily.

```
$ vagrant reload                                                                                                    
/Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/source.rb:140:in `rescue in load_specs': Invalid spec cache file in /Users/james/.gem/specs/rubygems.org%443/latest_specs.4.8 (Gem::Exception)
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/source.rb:132:in `load_specs'
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/spec_fetcher.rb:230:in `tuples_for'
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/spec_fetcher.rb:199:in `block in available_specs'
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/source_list.rb:55:in `each'
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/source_list.rb:55:in `each_source'
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/spec_fetcher.rb:195:in `available_specs'
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/spec_fetcher.rb:81:in `search_for_dependency'
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/spec_fetcher.rb:139:in `spec_for_dependency'
    from /Applications/Vagrant/embedded/lib/ruby/2.0.0/rubygems/dependency_installer.rb:156:in `find_gems_with_sources'
    from /Users/james/.vagrant.d/gems/gems/vagrant-omnibus-1.4.1/lib/vagrant-omnibus/config.rb:86:in `retrieve_latest_chef_version'
    from /Users/james/.vagrant.d/gems/gems/vagrant-omnibus-1.4.1/lib/vagrant-omnibus/config.rb:44:in `finalize!'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/config/v2/root.rb:50:in `block in finalize!'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/config/v2/root.rb:49:in `each'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/config/v2/root.rb:49:in `finalize!'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/config/v2/loader.rb:21:in `finalize'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/config/loader.rb:158:in `load'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/vagrantfile.rb:28:in `initialize'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:614:in `new'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:614:in `vagrantfile'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:399:in `host'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:198:in `block in action_runner'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:33:in `call'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:33:in `run'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:386:in `hook'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:596:in `unload'
    from /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.6.5/bin/vagrant:177:in `ensure in <main>'
    from /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.6.5/bin/vagrant:177:in `<main>'
```

**Comment by najamelan** [comment]
I was looking into this plugin because it can cache the chef install with vagrant-cachier. However if you have no internet connectivity, it makes all vagrant commands hang. It seems that currently this is not a solution to be able to use vagrant/chef offline...

**Comment by Saburesh07** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
