### ISSUE TITLE
Undefined method 'sh' for VagrantPlugins CommunicatorWinRM

### ISSUE THREAD

**Issue by chriskilding** [chef-boneyard/vagrant-omnibus#90]
This issue has been migrated from (#4249)[https://github.com/mitchellh/vagrant/issues/4249] in Vagrant core, after @sneal found it to be a bug with this plugin instead.

---

I got the following error when trying to provision a Windows Server 2008 R2 box with Chef Solo and vagrant-omnibus. A cursory look suggests something thought it was in *nix land and called 'sh' when it shouldn't have done.

The box I'm using is https://vagrantcloud.com/ferventcoder/win2008r2-x64-nocm. Running on Vagrant 1.6.3 / OSX 10.9 / latest Chef development kit with integrated Berkshelf.

```
==> windows: Mounting shared folders...
    windows: /vagrant => /Users/[me]/Documents/Git/rtsproto_backend
    windows: /tmp/vagrant-chef-2/chef-solo-1/cookbooks => /Users/[me]/.berkshelf/windows/vagrant/berkshelf-20140725-1855-1muei20-windows
==> windows: Forcing shutdown of VM...
==> windows: Destroying VM and associated drives...
==> windows: Running cleanup tasks for 'chef_solo' provisioner...
/Applications/Vagrant/embedded/gems/gems/vagrant-1.6.3/plugins/communicators/winrm/communicator.rb:76:in `execute': undefined method `sh' for #<VagrantPlugins::CommunicatorWinRM::WinRMShell:0x000001009dab10> (NoMethodError)
    from /Users/[me]/.vagrant.d/gems/gems/vagrant-omnibus-1.4.1/lib/vagrant-omnibus/action/install_chef.rb:144:in `installed_version'
...
```

**Comment by vinyar** [comment]
+1 just hit this as well. Adding below fixed the error. 

```ruby
   config.vm.guest = :windows
```

With that said, I would wager a guess that guest :windows is an artifact left behind to avoid breaking people after vagrant started officially supporting windows (I think guest :windows essentially translates into communicator = 'winrm'. It may go away at some point.

**Comment by sneal** [comment]
@vinyar Guest and Communicator seem similar, but are very different. For example, you can set the guest type to 'windows' and the communicator to 'ssh' assuming you've installed and configured an SSH server on your Windows guest.

**Comment by lonniev** [comment]
Thanks @sneal this also immediately fixed the omnibus issue for me for a Windows on Softlayer VM.

**Comment by Saburesh07** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
